ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# install nvblox in the container
RUN sudo apt update && \
    sudo apt-get install -y ros-humble-isaac-ros-nvblox && \
    rosdep update && \
    rosdep install isaac_ros_nvblox
